<a href="https://colab.research.google.com/github/MGhimiray/Python-libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Numpy and its functions

In [ ]:
import numpy as np

Using numpy for creating an array

In [ ]:
a=np.array([[1,2],[2,4],[5,6]])
print(a[1])

Creating an array in a particular range

In [10]:
np.arange(3,12,2)

array([ 3,  5,  7,  9, 11])

Sorting elements

In [12]:
a=np.array([8,59,6,45,100,57,1,34,64])
np.sort(a)

array([  1,   6,   8,  34,  45,  57,  59,  64, 100])

Concatenate arrays

In [18]:
a = np.array([[0, 6]])
b = np.array([[3, 6],[8, 10]])
np.concatenate((a, b), axis=0)

array([[ 0,  6],
       [ 3,  6],
       [ 8, 10]])

In [ ]:
Reshaping an array

In [21]:
a = np.array([4,8,9,6,7,1,0,2,3,5,6,5])
print(a)
b = a.reshape(4, 3)
print(b)

[4 8 9 6 7 1 0 2 3 5 6 5]
[[4 8 9]
 [6 7 1]
 [0 2 3]
 [5 6 5]]


Summing the elements

In [25]:
b = np.array([[8, 1], [4, 3]])
b.sum(axis=0)

array([12,  4])

Summing Matrices

In [28]:
a = np.array([[5, 4, 3], [7, 8, 6]])
b = np.array([[7, 9, 3], [4, 3, 1]])
c=a + b
print(c)

[[12 13  6]
 [11 11  7]]


Creating arrays with random integer numbers

In [31]:
a = np.random.randint(10, 50, 9)
print(a)

[18 41 24 10 28 16 24 37 10]


Creating arrays with random float values

In [33]:
a = np.random.random([10])
print(a)

[0.75298259 0.71320647 0.46392828 0.0384184  0.09874422 0.03509299
 0.90088323 0.3639531  0.93825301 0.25904596]
